### PR TITLE
Conformance results for v1.27/kind

### PR DESCRIPTION
**Pull request by heyste**
1.27 Test submission for [kind](https://kind.sigs.k8s.io/)

### CODE REVIEW

**Comment by heyste** [comment]
Historical testing

**Comment by BobyMCbobs** [comment]
opening for testing as version is out of date

**Comment by BobyMCbobs** [comment]
unable to use version &#39;v1.27&#39; because it is older than the last currently supported release (v1.28)

**Comment by BobyMCbobs** [comment]
Unable To Use Version V1.27 Because It Is Older Than The Last Currently Supported Release V1.28

**Comment by BobyMCbobs** [comment]
UNABLE TO USE VERSION V1.27 BECAUSE IT IS OLDER THAN THE LAST CURRENTLY SUPPORTED RELEASE V1.28

**Comment by BobyMCbobs** [comment]
Unable to use version v1.27 because it is older than the last currently supported release v1.28

**Comment by BobyMCbobs** [comment]
Almost got the pull request event trigger to be integrated. 
https://github.com/cncf-infra/k8s-conformance/actions/runs/9293744056/job/25577559010

**Comment by BobyMCbobs** [comment]
Unable to use version v1.27 because it is older than the last currently supported release v1.28.

**Pull request closed without merging**
